#include "compare_trait.h"

HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(signed char, schar);
HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(short, short);
HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(int, int);
HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(long, long);
HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(long long, llong);

HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(unsigned char, uchar);
HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(unsigned short, ushort);
HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(unsigned, uint);
HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(unsigned long, ulong);
HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(unsigned long long, ullong);

HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(size_t, size);
HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(ptrdiff_t, ptrdiff);

HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(char, char);
HLC_DEFINE_PRIMITIVE_COMPARE_INSTANCE(wchar_t, wchar);
